version: 0.2

env:
  parameter-store:
    STAGE_FLAGS: "/dbmaestro/stages/upgrade"
    PACKAGE_NAME: "V11"
phases:
  install:
    commands:
      - echo Installing Docker on Amazon Linux 2023...
      - yum update -y
      - yum install -y docker
      - systemctl start docker || service docker start || dockerd &
      - usermod -a -G docker ec2-user || true
  pre_build:
    commands:
      - export EXECUTE_UPGRADE=$(echo $STAGE_FLAGS | grep -o 'execute_upgrade=[^&]*' | cut -d= -f2)
      
  build:
    commands:
      - echo Building and running DBmaestro deployment container...
      - docker build -t dbmaestro-runner .
      - docker run dbmaestro-runner
  post_build:
    commands:
      - |
        if [ "$EXECUTE_UPGRADE" = "true" ]; then
          echo "Running upgrade for package: $PACKAGE_NAME"
          java -jar DBmaestroAgent.jar -Upgrade -ProjectName "PLANHUB_DEMO" -EnvName "Release Source" -PackageName "$PACKAGE_NAME" -BackupBehavior True -RestoreBehavior True -Server "DOPX-BERKE:8020" -AuthType DBmaestroAccount -UserName "poc@dbmaestro.com" -Password "7KI5tL3ywYAZLB8FUY9fzJyekemgtG45"
        else
          echo "Standard build process"
          docker build -t dbmaestro-runner .
        fi
