version: 0.2

phases:
  install:
    commands:
      - echo Installing Docker on Amazon Linux 2023...
      - yum update -y
      - yum install -y docker
      - systemctl start docker || service docker start || dockerd &
      - usermod -a -G docker ec2-user || true
  build:
    commands:
      - echo Building and running DBmaestro deployment container...
      - docker build -t dbmaestro-runner .
      - docker run dbmaestro-runner
